captainVersion: 4
services:
    $$cap_appname:
        caproverExtra:
            notExposeAsWebApp: 'true'
        image: coturn/coturn:$$cap_coturn_version
        ports:
            - 3478:3478
            - 5349:5349
            - 49152:49152
            - 49153:49153
            - 49154:49154
            - 49155:49155
            - 49156:49156
            - 49157:49157
            - 49158:49158
            - 49159:49159
            - 49160:49160
        restart: always
        volumes:
            - $$cap_coturn_config_filepath:/etc/coturn/turnserver.conf
caproverOneClickApp:
    variables:
        - id: $$cap_coturn_version
          label: Coturn Version
          defaultValue: 4.5.2-r11
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/coturn/coturn/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_coturn_config_filepath
          label: Required - coturn config path on a host machine.
          validRegex: /\/[^\s-][a-zA-Z0-9_\/-]*[^\/][^\s-]/
          description: Location of Coturn's configuration file
    instructions:
        start: >-
            The TURN Server is a VoIP media traffic NAT traversal server and gateway.
            Could be used as a general-purpose network traffic TURN server and gateway, too.
            
            Before configuring it in here, go and create config file on a host machine.
            F.ex.: touch /coturn.conf.
            For a full config reference check:
            https://github.com/coturn/coturn/blob/master/examples/etc/turnserver.conf 
            
            Host config updates will be reflected inside the Docker upon restart.
        end: >-
            Coturn is deployed and available at $$cap_root_domain.


            It has the following open ports: 3478, 5349, 49152-49160

            Please check your firewall configuration
    displayName: Coturn
    isOfficial: false
    description: Coturn is a TURN Server is a VoIP media traffic NAT traversal server and gateway.
    documentation: https://github.com/coturn/coturn
